# Generated by Django 2.1.4 on 2018-12-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181205_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', '미정'), ('1', '남성'), ('2', '여성')], max_length=1, null=True),
        ),
    ]
