# Generated by Django 2.1.4 on 2018-12-07 10:55

import clothes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('origin_img', models.ImageField(upload_to=clothes.models.user_path)),
                ('owner', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thumb_closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('t-shirts', 't-shirts'), ('pants', 'pants'), ('shoes', 'shoes'), ('tote bag', 'tote bag'), ('one-piece', 'one-piece'), ('sandals', 'sandals'), ('hat', 'hat'), ('glasses', 'glasses'), ('shirts', 'shirts'), ('skirt', 'skirt'), ('outer', 'outer'), ('sports shoes', 'sports shoes'), ('watch', 'watch'), ('swimming suit', 'swimming suit'), ('backpack', 'backpack'), ('baggage', 'baggage'), ('underwear bra', 'underwear bra'), ('underwear panty', 'underwear panty')], default=0, max_length=20, null=True)),
                ('thumb', models.CharField(max_length=100)),
                ('origin', models.ForeignKey(on_delete='CASCADE', to='clothes.Closet')),
            ],
        ),
    ]
