# Generated by Django 2.1.4 on 2018-12-07 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumb_closet',
            name='owner',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='closet',
            name='owner',
            field=models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thumb_closet',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
